version: '3.4'
services:
  postgres_db:
    container_name: database_container
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  restserver:
    container_name: rest_server_container  
    build: ./webserver
    ports:
      - "5000:5000"

volumes:
  pg_data:
