version: '3.4'
services:
  postgres_db:
    container_name: database_container
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  restserver:
    container_name: rest_server_container  
    build: .
    ports:
      - "5000:5000"

volumes:
  pg_data:
